import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { AdminProvider } from '@/context/admin.context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='icon'
          href='/assets/favicon.png'
          sizes='any'
        />
      </head>
      <body className={inter.className}>
        <AdminProvider>{children}</AdminProvider>
      </body>
    </html>
  );
}
